# Generated by Django 5.2.6 on 2025-09-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourstore', '0002_product_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Wearables', 'Wearables'), ('SmartPhone', 'SmartPhone'), ('Laptop', 'Laptop'), ('Camera', 'Camera'), ('Audio', 'Audio'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('Monitor', 'Monitor'), ('Processor', 'Processor'), ('Graphics Card', 'Graphics Card')], default='N/A', max_length=50),
        ),
    ]
